# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/levakuz/.local/lib/python2.7/site-packages/cmake/data/bin/cmake

# The command to remove a file.
RM = /home/levakuz/.local/lib/python2.7/site-packages/cmake/data/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/levakuz/rabbitmq_cpp_connect

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/levakuz/rabbitmq_cpp_connect

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/levakuz/.local/lib/python2.7/site-packages/cmake/data/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/levakuz/.local/lib/python2.7/site-packages/cmake/data/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/levakuz/rabbitmq_cpp_connect/CMakeFiles /home/levakuz/rabbitmq_cpp_connect//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/levakuz/rabbitmq_cpp_connect/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named send_test_message

# Build rule for target.
send_test_message: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 send_test_message
.PHONY : send_test_message

# fast build rule for target.
send_test_message/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/send_test_message.dir/build.make CMakeFiles/send_test_message.dir/build
.PHONY : send_test_message/fast

#=============================================================================
# Target rules for targets named connect_test

# Build rule for target.
connect_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 connect_test
.PHONY : connect_test

# fast build rule for target.
connect_test/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connect_test.dir/build.make CMakeFiles/connect_test.dir/build
.PHONY : connect_test/fast

#=============================================================================
# Target rules for targets named amqpcpp-static

# Build rule for target.
amqpcpp-static: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 amqpcpp-static
.PHONY : amqpcpp-static

# fast build rule for target.
amqpcpp-static/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/build
.PHONY : amqpcpp-static/fast

#=============================================================================
# Target rules for targets named amqpcpp

# Build rule for target.
amqpcpp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 amqpcpp
.PHONY : amqpcpp

# fast build rule for target.
amqpcpp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/build
.PHONY : amqpcpp/fast

include/AMQP.o: include/AMQP.cpp.o
.PHONY : include/AMQP.o

# target to build an object file
include/AMQP.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQP.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQP.cpp.o
.PHONY : include/AMQP.cpp.o

include/AMQP.i: include/AMQP.cpp.i
.PHONY : include/AMQP.i

# target to preprocess a source file
include/AMQP.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQP.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQP.cpp.i
.PHONY : include/AMQP.cpp.i

include/AMQP.s: include/AMQP.cpp.s
.PHONY : include/AMQP.s

# target to generate assembly for a file
include/AMQP.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQP.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQP.cpp.s
.PHONY : include/AMQP.cpp.s

include/AMQPBase.o: include/AMQPBase.cpp.o
.PHONY : include/AMQPBase.o

# target to build an object file
include/AMQPBase.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQPBase.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQPBase.cpp.o
.PHONY : include/AMQPBase.cpp.o

include/AMQPBase.i: include/AMQPBase.cpp.i
.PHONY : include/AMQPBase.i

# target to preprocess a source file
include/AMQPBase.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQPBase.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQPBase.cpp.i
.PHONY : include/AMQPBase.cpp.i

include/AMQPBase.s: include/AMQPBase.cpp.s
.PHONY : include/AMQPBase.s

# target to generate assembly for a file
include/AMQPBase.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQPBase.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQPBase.cpp.s
.PHONY : include/AMQPBase.cpp.s

include/AMQPException.o: include/AMQPException.cpp.o
.PHONY : include/AMQPException.o

# target to build an object file
include/AMQPException.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQPException.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQPException.cpp.o
.PHONY : include/AMQPException.cpp.o

include/AMQPException.i: include/AMQPException.cpp.i
.PHONY : include/AMQPException.i

# target to preprocess a source file
include/AMQPException.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQPException.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQPException.cpp.i
.PHONY : include/AMQPException.cpp.i

include/AMQPException.s: include/AMQPException.cpp.s
.PHONY : include/AMQPException.s

# target to generate assembly for a file
include/AMQPException.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQPException.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQPException.cpp.s
.PHONY : include/AMQPException.cpp.s

include/AMQPExchange.o: include/AMQPExchange.cpp.o
.PHONY : include/AMQPExchange.o

# target to build an object file
include/AMQPExchange.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQPExchange.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQPExchange.cpp.o
.PHONY : include/AMQPExchange.cpp.o

include/AMQPExchange.i: include/AMQPExchange.cpp.i
.PHONY : include/AMQPExchange.i

# target to preprocess a source file
include/AMQPExchange.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQPExchange.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQPExchange.cpp.i
.PHONY : include/AMQPExchange.cpp.i

include/AMQPExchange.s: include/AMQPExchange.cpp.s
.PHONY : include/AMQPExchange.s

# target to generate assembly for a file
include/AMQPExchange.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQPExchange.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQPExchange.cpp.s
.PHONY : include/AMQPExchange.cpp.s

include/AMQPMessage.o: include/AMQPMessage.cpp.o
.PHONY : include/AMQPMessage.o

# target to build an object file
include/AMQPMessage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQPMessage.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQPMessage.cpp.o
.PHONY : include/AMQPMessage.cpp.o

include/AMQPMessage.i: include/AMQPMessage.cpp.i
.PHONY : include/AMQPMessage.i

# target to preprocess a source file
include/AMQPMessage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQPMessage.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQPMessage.cpp.i
.PHONY : include/AMQPMessage.cpp.i

include/AMQPMessage.s: include/AMQPMessage.cpp.s
.PHONY : include/AMQPMessage.s

# target to generate assembly for a file
include/AMQPMessage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQPMessage.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQPMessage.cpp.s
.PHONY : include/AMQPMessage.cpp.s

include/AMQPQueue.o: include/AMQPQueue.cpp.o
.PHONY : include/AMQPQueue.o

# target to build an object file
include/AMQPQueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQPQueue.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQPQueue.cpp.o
.PHONY : include/AMQPQueue.cpp.o

include/AMQPQueue.i: include/AMQPQueue.cpp.i
.PHONY : include/AMQPQueue.i

# target to preprocess a source file
include/AMQPQueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQPQueue.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQPQueue.cpp.i
.PHONY : include/AMQPQueue.cpp.i

include/AMQPQueue.s: include/AMQPQueue.cpp.s
.PHONY : include/AMQPQueue.s

# target to generate assembly for a file
include/AMQPQueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp-static.dir/build.make CMakeFiles/amqpcpp-static.dir/include/AMQPQueue.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/amqpcpp.dir/build.make CMakeFiles/amqpcpp.dir/include/AMQPQueue.cpp.s
.PHONY : include/AMQPQueue.cpp.s

src/connect_test.o: src/connect_test.cpp.o
.PHONY : src/connect_test.o

# target to build an object file
src/connect_test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connect_test.dir/build.make CMakeFiles/connect_test.dir/src/connect_test.cpp.o
.PHONY : src/connect_test.cpp.o

src/connect_test.i: src/connect_test.cpp.i
.PHONY : src/connect_test.i

# target to preprocess a source file
src/connect_test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connect_test.dir/build.make CMakeFiles/connect_test.dir/src/connect_test.cpp.i
.PHONY : src/connect_test.cpp.i

src/connect_test.s: src/connect_test.cpp.s
.PHONY : src/connect_test.s

# target to generate assembly for a file
src/connect_test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/connect_test.dir/build.make CMakeFiles/connect_test.dir/src/connect_test.cpp.s
.PHONY : src/connect_test.cpp.s

src/send_test_message.o: src/send_test_message.cpp.o
.PHONY : src/send_test_message.o

# target to build an object file
src/send_test_message.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/send_test_message.dir/build.make CMakeFiles/send_test_message.dir/src/send_test_message.cpp.o
.PHONY : src/send_test_message.cpp.o

src/send_test_message.i: src/send_test_message.cpp.i
.PHONY : src/send_test_message.i

# target to preprocess a source file
src/send_test_message.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/send_test_message.dir/build.make CMakeFiles/send_test_message.dir/src/send_test_message.cpp.i
.PHONY : src/send_test_message.cpp.i

src/send_test_message.s: src/send_test_message.cpp.s
.PHONY : src/send_test_message.s

# target to generate assembly for a file
src/send_test_message.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/send_test_message.dir/build.make CMakeFiles/send_test_message.dir/src/send_test_message.cpp.s
.PHONY : src/send_test_message.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... amqpcpp"
	@echo "... amqpcpp-static"
	@echo "... connect_test"
	@echo "... send_test_message"
	@echo "... include/AMQP.o"
	@echo "... include/AMQP.i"
	@echo "... include/AMQP.s"
	@echo "... include/AMQPBase.o"
	@echo "... include/AMQPBase.i"
	@echo "... include/AMQPBase.s"
	@echo "... include/AMQPException.o"
	@echo "... include/AMQPException.i"
	@echo "... include/AMQPException.s"
	@echo "... include/AMQPExchange.o"
	@echo "... include/AMQPExchange.i"
	@echo "... include/AMQPExchange.s"
	@echo "... include/AMQPMessage.o"
	@echo "... include/AMQPMessage.i"
	@echo "... include/AMQPMessage.s"
	@echo "... include/AMQPQueue.o"
	@echo "... include/AMQPQueue.i"
	@echo "... include/AMQPQueue.s"
	@echo "... src/connect_test.o"
	@echo "... src/connect_test.i"
	@echo "... src/connect_test.s"
	@echo "... src/send_test_message.o"
	@echo "... src/send_test_message.i"
	@echo "... src/send_test_message.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

